# Generated by Django 5.0.3 on 2024-05-17 00:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('favorite_genre', models.CharField(choices=[('AC', 'Action'), ('AD', 'Adventure'), ('CO', 'Comedy'), ('DR', 'Drama'), ('FA', 'Fantasy'), ('HO', 'Horror'), ('MY', 'Mystery'), ('RO', 'Romance'), ('SC', 'Sci-Fi'), ('TH', 'Thriller')], default='RO', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
